### ISSUE TITLE
I'm getting a error with the latest version

### ISSUE THREAD

**Issue by mcplaysnlENG** [rhys19/Tornado-Script-FiveM#8]
I'm getting this error when i load up the latest release can you fix this?
![image](https://user-images.githubusercontent.com/61947308/128718303-018d2cff-b13d-44ed-8939-53fc703372ec.png)
![image](https://user-images.githubusercontent.com/61947308/128718333-0b86ff95-9dbe-4660-ae5b-332210b9f99d.png)

**Comment by rhys19** [comment]
did you replace all files? and restart your server afterwards?

**Comment by rhys19** [comment]
it's spitting out an error from the old version checker in server.lua but that doesn't exist in the newer version the new version checker is in a different file called `version.lua`

**Comment by rhys19** [comment]
Fixed in 2.1.5 make sure to update | https://github.com/rhys19/Tornado-Script-FiveM/releases/tag/2.1.5
